import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import other.utils.StringUtils;

import models.Activity;
import models.ChangedUrl;
import models.Course;
import models.CourseSection;
import models.KeyValueData;
import models.Question;
import models.SessionPart;
import models.SocialUser;
import models.StudySession;
import play.Play;
import play.jobs.Job;
import play.jobs.OnApplicationStart;
import play.mvc.Router;
import play.test.Fixtures;

@OnApplicationStart
public class CreateChangedUrls extends Job {
	private String chapters[][] = {
			{"Programming Methodologies Using Java - Lecture 1", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture01.pdf", "Topics: Welcome to CS106A, Course Staff, Why is the class called Programming Methodology?, Are you in the right class?, Class Logistics, Assignments and Grading, Extensions, Midterm and Final, Grade Breakdown, The Honor Code, Why Karel?", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/KkMDCCdjyW8\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture01.mp4.torrent?FC70D4D40F781ECFBAF3D3FDE7BB75416106EB32"}, 
			{"Programming Methodologies Using Java - Lecture 2", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture02.pdf", "Topics: Handout Information, Section Sign-up, Karel Commands, An Algorithm vs Program, Syntax of a Karel Program, Running a Karel Program, Creating Methods, SuperKarel, A for Loop, A While Loop, Karel Conditions, If Statement, Putting it All Together", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/0LoKDDRlfZc\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture02.mp4.torrent?2901C02F880A8E00D36F87AA24F1601A4B77C35E"},
			{"Programming Methodologies Using Java - Lecture 3", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture03.pdf", "Topics: Karel and Java, Common Errors, Comments, Pre-conditions and Post-conditions, Decomposition, The DoubleBeepers Example, Importance of Good Software Engineering, The Right Decomposition, The CleanUpKarel Example", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/C5HeRliZ0Ns\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture03.mp4.torrent?5C0D8CF221FC0676C68478B9CD4C95B12D2B3F1A"},
			{"Programming Methodologies Using Java - Lecture 4", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture04.pdf", "Topics: The History of Computing, Computer Science vs Programming, What Does the Computer Understand?, The Compilation Process, Java is an Object Oriented Language, Inheritance, Instance of a Class, The acm.program Hierarchy, Your First Java Program, A ConsoleProgram Example, The Graphics Window, The Sending-Messages-to-a-GLabel Example", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/nWheM30THaY\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture04.mp4.torrent?241FDD49D893DE4D293AE9B14D76758503CC0397"}, 
			{"Programming Methodologies Using Java - Lecture 5", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture05.pdf", "Topics: Variables, Data Types for Variables, Syntax for Using Variables, Classes as Types, Objects as Variables, Invoking Methods on Objects, Graphics Coordinates, Operations on the GObject Class and its Subclasses, Drawing Geometrical Objects, A FunGraphics Example, Expressions and Operators", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/NPzPnycCFuE\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture05.mp4.torrent?792FEFF8EC38CD41BE5DF7A698AD55649BF161B6"}, 
			{"Programming Methodologies Using Java - Lecture 6", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture06.pdf", "Topics: readInt() and readDouble(), The Division Operator w.r.t ints and Doubles, Order of Precedence for Operators, Type Casting, Shorthands, Constants, The Boolean Data Type, Value Comparisons, Boolean Expressions, Short Circuit Evaluation, Statement Blocks, Scope of Variables, Cascading if, The Switch Statement, The For Loop, The While Loop", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/GPWah4wbwYs\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture06.mp4.torrent?84D688F1C29F1D36940E65269B93A862987734BF"}, 
			{"Programming Methodologies Using Java - Lecture 7", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture07.pdf", "Topics: The Loop and a Half Problem, For Versus While Loop, The CheckerBoard Program Example, Methods in Java, Examples of Methods, The FactorialExample Program, Returning Objects from Methods.", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/3oM9yT9kBBc\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture07.mp4.torrent?7A8EFE5764AD3F1D06F2B3B79F3DB27E03535AF4"}, 
			{"Programming Methodologies Using Java - Lecture 8", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture08.pdf", "Topics: Information Hiding, The Void Return Type, Parameter Passing Between Methods, Bad Times with Methods, Using Classes, Instance variables vs Local Variables, The RandomGenerator Program Example, The RollDice Program Example, The setSeed() Method", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/W2ysz_6AyJE\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture08.mp4.torrent?1E1DBCC61610B971808E630F3F8EE689DB34BF49"}, 
			{"Programming Methodologies Using Java - Lecture 9", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture09.pdf", "Topics: Strings, Writing Your Own Class, Public and Private Visibility, Creating a New Class, The Constructor Method, Shadowing of Variables and the 'this' Keyword, Using the Created Class, Objects are Called by Reference not Called by Value, Class Variables, The JavaDoc, The Student Program Example", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/iYtri45lhtc\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture09.mp4.torrent?856A22A0F17CDF7CBB2D08AB3DA8CE5BB0133B19"}, 
			{"Programming Methodologies Using Java - Lecture 10", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture10.pdf", "Topics: Importance of Private Variables, Extending the Student Class, Overriding Methods, The acm.graphics Package, GCanvas, Methods Common to All GObjects, Interfaces and Methods Defined by Them, The BouncingBall Program Example, The Geometry of the GLabel Class, The GArc Class", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/YpZCKVG4s5k\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture10.mp4.torrent?5F8EDAB31A195B50BD56517BD60AF084DEFA71B4"}, 
			{"Programming Methodologies Using Java - Lecture 11", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture11.pdf", "Topics: The GImage Class, The GPolygon Class, The GCompound Class, Event Driven Programs, The ClickForFace Program Example, Responding to Mouse Events, Responding to Keyboard Events, The UFO program Example", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/Iua9Klr0lfo\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture11.mp4.torrent?C2BF0741BFC9F4EE1A8E3A38808541F4F017E8D8"}, 
			{"Programming Methodologies Using Java - Lecture 12", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture12.pdf", "Topics: Enumeration, Characters, The ASCII Subset of Unicode, Reading Characters, Math on Characters, char as a Primitive Type; the Character Class, Strings and Their Manipulations", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/GIP9MPFJmhI\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture12.mp4.torrent?A3CF0EC9A091206ECDD23BA73D16CEF080F9B290"},
			{"Programming Methodologies Using Java - Lecture 13", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture13.pdf", "Topics: String Processing, Tokenizers, Encryption", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/QUrz8-Ltc-s\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture13.mp4.torrent?F378CE55F83196A06217C77EF85C78C68BFEBFF3"},
			{"Programming Methodologies Using Java - Lecture 14", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture14.pdf", "Topics: Memory, Different Sections of Memory for Different Types of Variables, Memory Allocation Mechanics, The Pointer Viewpoint, The Binky Pointer Fun Video", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/W8nNdNZ40EQ\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture14.mp4.torrent?3B6856B0A109E1A56672CBB5ABF011FCC5F01438"}, 
			{"Programming Methodologies Using Java - Lecture 15", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture15.pdf", "Topics: Pointer Recap, Why are Objects 'Call by Reference' Instead of 'Call of Value'?, Wrapper Classes for Primitive Types, Files, Code for Opening, Reading and Closing Files, Exceptions, Code for Writing Files", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/ttbu9L4RdYs\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture15.mp4.torrent?F554CC00AB84340BD095AB2AA5362DDA98C2C2C1"}, 
			{"Programming Methodologies Using Java - Lecture 16", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture16.pdf", "Topics: Array, Creating a New Array, The ++ Operator, Actual Size / Effective Size of the Array, An Array as a Parameter, Initialize an Array During Creation, An ArrayList", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/FUO3XEUVydk\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture16.mp4.torrent?C20FAA910158013E739909AB9802FDE041D4BBDB"}, 
			{"Programming Methodologies Using Java - Lecture 17", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture17.pdf", "Topics: Multi-dimensional Arrays, An ArrayList, The Template Class, Methods in the ArrayList Class, An Example Program Using ArrayList, ArrayLists Hold Objects, An Example Program with an ArrayList of Glabels, The GrayImage Example Program", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/YJ9FlCFi3c8\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture17.mp4.torrent?9C5F805FEDB43AA261C15742BFC4BB9D0C7F4B0E"}, 
			{"Programming Methodologies Using Java - Lecture 18", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture18.pdf", "Topics: A Wrap Up of Multi-dimensional Arrays, The ArrayList Way, Pros and Cons : ArrayList vs. Array, Debugging, Approaches to Debugging, The Debugger in Eclipse", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/9xnLnDa04dM\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture18.mp4.torrent?992203C22A77F5B3BCF900861306BFE6E085637D"}, 
			{"Programming Methodologies Using Java - Lecture 19", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture19.pdf", "Topics: An Interface, How are Interfaces Implemented, A Map, The HashMap Class, Methods of the HashMap, The Collection Hierarchy, The Map Hierarchy, An Iterator, A HashMap Example", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/MxBx1km7WNk\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture19.mp4.torrent?4762B7E056DA37D583D11D7EFE1A8E1F55B86963"}, 
			{"Programming Methodologies Using Java - Lecture 20", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture20.pdf", "Topics: GUI, Interactors in the Context of a Java Program, The Swing Interactor Hierarchy, Window Regions, Creating Interactors, Example Programs, Exploring More Interactors, The InteractiveDrawFace Program Example", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/b8OLOWWxvx0\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture20.mp4.torrent?9DA969D3B4C75D203C71D2868D593E915E3EC71F"}, 
			{"Programming Methodologies Using Java - Lecture 21", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture21.pdf", "Topics: Review of Interactors and Listeners, Example Programs, The Use of the Two Ways Shown in the Examples - Using getSouce and getActionCommand, TextField Example, Layouts, The Temperature Conversion Example, The TextAndGraphics Example", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/RJfQK6iAN4M\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture21.mp4.torrent?993A54C3A20264F451DC8B655538B37B982D9FAF"}, 
			{"Programming Methodologies Using Java - Lecture 22", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture22.pdf", "Topics: Overview of NameSurfer - The Next Assignment, Components and Containers, Listeners for Components, Create a Program Which Extends Program, The ComponentListener Interface, The MusicShop Example Program, The MusicShopDisplay Example Program", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/AGUUQXO8eXk\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture22.mp4.torrent?A1CE84BAC477E1290F0766010D832199F827429D"},
			{"Programming Methodologies Using Java - Lecture 23", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture23.pdf", "Topics: Introduction to Lecture's material - Searching, Sorting and Algorithmic Efficiency, Searching, Linear Search, Efficiency of Linear Search, Binary Search, Efficiency of Binary Search, Comparing Search Efficiencies, Sorting, The Selection Sort Algorithm, Efficiency of Selection Sort, The Radix Sort Algorithm", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/4ytrc3AsaHM\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture23.mp4.torrent?5796C2693FB24311B7554E9EA9F392BBEDEDFAC2"},
			{"Programming Methodologies Using Java - Lecture 24", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture24.pdf", "Topics: Principles of Good Software Engineering for Managing Large Amounts of Data, Principles of Design, The Collection Hierarchy, Useful Methods of Collection, The FlyTunes Example Program - An Online Music Store, Defining the Song Class, Defining the Album Class, Seeing the Program Run, Considering the Data Structures Needed, Reusing Data - Shallow Copy vs. Deep Copy, The FlyTunesStore Program Code", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/lYZwJ6xyGNc\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture24.mp4.torrent?95C41C59059291EED19C5A82D23A599C2A7CE7C1"}, 
			{"Programming Methodologies Using Java - Lecture 25", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture25.pdf", "Topics: Defining a Social Network for Our Purposes, See What the Program Needs to Do, The Six Degrees of Separation Phenomenon, Concurrency, A Thread, The Runnable Interface, Creating a Thread, Example Program, Having Shared Data Between Your Threads", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/YuVrg0RiPmM\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture25.mp4.torrent?0592943B36410FDA3C7855DCFD3E525D0624A695"}, 
			{"Programming Methodologies Using Java - Lecture 26", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture26.pdf", "Topics: Introduction to the Standard Java Libraries, A JAR File, Creating a JAR File, Creating an Applet, Standard Java Programs Without Using the ACM Libraries, Other Resources - Learning More Java", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/Qi6L9lfbyyQ\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture26.mp4.torrent?EA7301A04CC2FFE8CE4BDD262398B393DEC7EEEC"}, 
			{"Programming Methodologies Using Java - Lecture 27", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture27.pdf", "Topics: Life After CS106A, The CS Major, Other Possible Majors", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/aIjM-UE1JDQ\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture27.mp4.torrent?D7DFE1132979FF33F0AE191DA997CFB0E482BA2A"}, 
			{"Programming Methodologies Using Java - Lecture 28", "http://see.stanford.edu/materials/icspmcs106a/transcripts/ProgrammingMethodology-Lecture28.pdf", "Topics: The Graphics Contest Winners, Review for the Final, Example Question 1, Example Question 2, A Wrap-up", "<iframe width=\"480\" height=\"390\" src=\"http://www.youtube.com/embed/Kfc5O8hVzLQ\" frameborder=\"0\" allowfullscreen></iframe>", "http://coursetorrent.stanford.edu:6969/torrents/cs106a-lecture28.mp4.torrent?CB499B2A31305C24840A6EE3A1BC20A428385AA8"},
			};
	
			String courseSanitizedTitle = "programming-methodologies-Using Java";
			
			String contentTemplate = "<p>%s</p><p>%s</p><p><a href=\"%s\">Download mp4 Video (Torrent)</a></p><p><a href=\"%s\">Lecture transcripts</a></p>";
			
	public void doJob() {
		Course course = Course.findBySanitizedTitle(courseSanitizedTitle);
		if(course != null) {
			for (int i=0; i<chapters.length; i++) {
				String contents = String.format(contentTemplate, chapters[i][2], chapters[i][3], chapters[i][4], chapters[i][1]);
				CourseSection courseSection = new CourseSection(course, chapters[i][0], contents);
				courseSection.placement = i + 1;
				courseSection.save();
			}
		}
	}
}
